### ISSUE TITLE
JUnit plugin update 1.2 -> 1.3 breaks Integrity plugin

### ISSUE THREAD

**Issue by S1artie** [integrity-tf/jenkins#1]
java.lang.NoClassDefFoundError: hudson/tasks/test/DefaultTestResultParserImpl$1
         at hudson.tasks.test.DefaultTestResultParserImpl.parseResult(DefaultTestResultParserImpl.java:77)
         at hudson.tasks.test.TestResultParser.parse(TestResultParser.java:145)
         at de.gebit.integrity.IntegrityTestResultRecorder.perform(IntegrityTestResultRecorder.java:87)
         at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
         at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
         at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
         at hudson.model.Build$BuildExecution.post2(Build.java:183)
         at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
         at hudson.model.Run.execute(Run.java:1770)
         at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
         at hudson.model.ResourceController.execute(ResourceController.java:89)
         at hudson.model.Executor.run(Executor.java:240)

**Comment by S1artie** [comment]
Issue was reported to me. Could not be reproduced; tested with the most current version 1.4. Even if 1.3 should not work - 1.4 works, so I consider this being fine.
