### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Mroehs** [integrity-tf/jenkins#13]
After updating from the Integrity Jenkins plug-in 0.9.4 to 0.10.1 I am receiving the following NPE:

`ERROR: Publisher de.gebit.integrity.IntegrityTestResultRecorder aborted due to exception
java.lang.NullPointerException
    at de.gebit.integrity.IntegrityCompoundTestResult.getXmlFile(IntegrityCompoundTestResult.java:121)
    at de.gebit.integrity.IntegrityCompoundTestResult.persistChildren(IntegrityCompoundTestResult.java:152)
    at de.gebit.integrity.IntegrityCompoundTestResult.writeObject(IntegrityCompoundTestResult.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
    at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
    at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
    at java.io.ObjectOutputStream.writeObject(Unknown Source)
    at hudson.remoting.UserRequest._serialize(UserRequest.java:155)
    at hudson.remoting.UserRequest.serialize(UserRequest.java:164)
    at hudson.remoting.UserRequest.perform(UserRequest.java:126)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:328)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1$1.run(Engine.java:63)
    at java.lang.Thread.run(Unknown Source)`

I am running Jenkins version 1.553.

**Comment by S1artie** [comment]
It is possible that there is an incompatibility with older Jenkins versions. The inner workings of Jenkins change from time to time, and it is pretty much impossible to tell whether a plug-in works with any version of Jenkins short of simply trying it. I typically test the plugin on the up-to-date version when developing and releasing it, and since the 0.10.x branch is newer, I used a much newer version with this than 1.553.

Could you try with an up-to-date Jenkins version and the same result files, whether this results in the same error?

**Comment by Mroehs** [comment]
As the build server is also used by other teams, I cannot just update it. I will clarify if it's ok to do an update.

**Comment by Mroehs** [comment]
Sadly an update of our Jenkins in production environment is currently not possible :(
Sorry for that. 
I will come back when we performed an update.
