### ISSUE TITLE
Testresult data serialized into build.xml and integrityResultData.xml

### ISSUE THREAD

**Issue by cpfeiffer** [integrity-tf/jenkins#25]
We were still using version 0.12.1 and noticed that the compressed and base64 encoded test results are written to both build.xml *and* integrityResultData.xml:
```
-rw-r--r-- 1 jenkins jenkins 68M Mär 25 13:02 ./3986/build.xml
-rw-r--r-- 1 jenkins jenkins 68M Mär 25 13:02 ./3986/integrityResultData.xml
```
The `<rawData>` contents is the same for both. I would suppose that build.xml should not contain the rawData at all.

The reason why I'm looking at this at all is that we see performance issues when Jenkins discards old builds, and we always have this in the stack and we're wondering if is deserializing too much.
```
at java.util.Arrays.copyOf(java.base@11.0.10/Arrays.java:3745)
at java.io.ByteArrayOutputStream.grow(java.base@11.0.10/ByteArrayOutputStream.java:120)
at java.io.ByteArrayOutputStream.ensureCapacity(java.base@11.0.10/ByteArrayOutputStream.java:95)
at java.io.ByteArrayOutputStream.write(java.base@11.0.10/ByteArrayOutputStream.java:137)
- locked <0x00000007ff843c00> (a java.io.ByteArrayOutputStream)
at com.thoughtworks.xstream.core.util.Base64Encoder.decode(Base64Encoder.java:77)
at com.thoughtworks.xstream.converters.extended.EncodedByteArrayConverter.fromString(EncodedByteArrayConverter.java:81)
at com.thoughtworks.xstream.converters.extended.EncodedByteArrayConverter.unmarshal(EncodedByteArrayConverter.java:49)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.converters.reflection.SerializableConverter$2.defaultReadObject(SerializableConverter.java:413)
at com.thoughtworks.xstream.core.util.CustomObjectInputStream.defaultReadObject(CustomObjectInputStream.java:116)
at de.gebit.integrity.IntegrityTestResult.readObject(IntegrityTestResult.java:129)

[... MANY further elemets in the stack...]

at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:346)
at jenkins.model.lazy.LazyLoadRunMapEntrySet$1.next(LazyLoadRunMapEntrySet.java:74)
at jenkins.model.lazy.LazyLoadRunMapEntrySet$1.next(LazyLoadRunMapEntrySet.java:63)
at java.util.AbstractMap$2$1.next(java.base@11.0.10/AbstractMap.java:418)
at hudson.util.RunList.size(RunList.java:123)
at hudson.tasks.LogRotator.perform(LogRotator.java:160)
at hudson.model.Job.logRotate(Job.java:469)
at hudson.maven.MavenModuleSet.logRotate(MavenModuleSet.java:920)
at jenkins.model.JobGlobalBuildDiscarderStrategy.apply(JobGlobalBuildDiscarderStrategy.java:54)
at jenkins.model.BackgroundGlobalBuildDiscarder.lambda$processJob$0(BackgroundGlobalBuildDiscarder.java:67)
at jenkins.model.BackgroundGlobalBuildDiscarder$$Lambda$788/0x0000000801797840.accept(Unknown Source)
```

**Comment by S1artie** [comment]
This appears to have been caused by a Jenkins update (version 2.266+) which changed the XStream internals. Due to JEP-228 (https://github.com/jenkinsci/jep/blob/master/jep/228/README.adoc) the XStream annotations used on IntegrityCompoundTestResult do not work automatically anymore and must be manually parsed. These annotations are used to prevent rawData inclusion in the build.xml main file.

Note that due to variations in plugin load order, it was even possible for this breakage to occur with older Jenkins versions than 2.266: the first plugin that performs manual annotation registration effectively stopped automatic processing for all subsequently loaded plugins. It is thus very likely that other plugins also added manual registration code as a fix for JEP-228-originated issues, which in turn can cause the issue with the Integrity plugin on older Jenkins versions.
