### ISSUE TITLE
Exception when parsing test results on build slaves

### ISSUE THREAD

**Issue by S1artie** [integrity-tf/jenkins#8]
```
Recording Integrity Test Results
ERROR: Failed to archive test reports
java.io.IOException: remote file operation failed: /home/jenkins/workspace/xxx at hudson.remoting.Channel@8e3d98e:Local Docker-f899bbe6be02: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@5fd71032
         at hudson.FilePath.act(FilePath.java:985)
         at hudson.FilePath.act(FilePath.java:967)
         at hudson.tasks.test.DefaultTestResultParserImpl.parseResult(DefaultTestResultParserImpl.java:77)
         at hudson.tasks.test.TestResultParser.parse(TestResultParser.java:145)
         at de.gebit.integrity.IntegrityTestResultRecorder.perform(IntegrityTestResultRecorder.java:108)
         at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
         at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
         at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
         at hudson.model.Build$BuildExecution.post2(Build.java:183)
         at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
         at hudson.model.Run.execute(Run.java:1743)
         at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
         at hudson.model.ResourceController.execute(ResourceController.java:89)
         at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@5fd71032
         at hudson.remoting.UserRequest.serialize(UserRequest.java:169)
         at hudson.remoting.UserRequest.<init>(UserRequest.java:63)
         at hudson.remoting.Channel.call(Channel.java:750)
         at hudson.FilePath.act(FilePath.java:978)
         ... 13 more
Caused by: java.io.NotSerializableException: hudson.model.FreeStyleBuild
         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
         at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
         at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
         at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
         at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
         at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
         at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
         at hudson.remoting.UserRequest._serialize(UserRequest.java:158)
         at hudson.remoting.UserRequest.serialize(UserRequest.java:167)
         ... 16 more
Build step 'Publish Integrity Test Results' changed build result to FAILURE
```

**Comment by S1artie** [comment]
fixed by commit f40be4fdaf6b5acc0ece7118def68590240f5278
